In [4]:
from PIL import Image
import os, glob, numpy as np
from sklearn.model_selection import train_test_split

groups_folder_path = '../Data/image2npy_test'
categories = ["Drowsy","NonDrowsy"] # 이미지가 클래스명으로 되어있어야 하네;
nb_classes = len(categories) #카테고리갯수: 2개

#image_w = 227 #이미지의 크기를 모두 통일해준다
#image_h = 227

X = []
y = []
for idx, cat in enumerate(categories):
    
    #one-hot 돌리기.
    label = [0 for i in range(nb_classes)] # one-hot으로 라벨을 붙혀줌
    label[idx] = 1

    image_dir = groups_folder_path + "/" + cat
    #print(image_dir)
    files = glob.glob(image_dir+"/*.png")
    #print(files)
    print(cat, " 파일 길이 : ", len(files))
    for i, f in enumerate(files):
        img = Image.open(f)      #폴더를 열어주고 이미지를 읽음
        #img = img.convert("RGB")   #RGB로 바꿈
        #img = img.resize((image_w, image_h)) #이미지 크기를 모두 학습시키기 쉽게 64x64크기고
        data = np.asarray(img) #숫자로

        X.append(data) #리스트에 추가 
        y.append(label)


Drowsy  파일 길이 :  3
NonDrowsy  파일 길이 :  3


In [16]:
testx = np.array(X)
testx.shape

# 총 이미지 개수, 이미지 H, 이미지 W, RGB 채널

(6, 227, 227, 3)

In [17]:
testy = np.array(y)
testy.shape

(6, 2)

In [18]:
scence = (1000, 3, 400, 400)
cate = (6, 1, 1000, 1)

In [21]:
zz = (np.array([scence]), cate)

In [22]:
zz

(array([[1000,    3,  400,  400]]), (6, 1, 1000, 1))

In [11]:
X = np.array(X)
y = np.array(y)
#1 0 0 0 이면 느타리버섯
#0 1 0 0 이면 새송이버섯

#X_train, X_test, y_train, y_test = train_test_split(X, y) #데이터를 훈련셋과 시험셋으로 나눠주는 함수이용
#xy = (X_train, X_test, y_train, y_test)

xy = (X, y)

#np.save("multi_image_data.npy", xy) #그렇게 xy를 multi_image_data.npy로 저장

print("ok", len(y))

ok 6


In [2]:
import numpy as np
dataset = [
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8],
    [11, 9, 2, 10,  8]
]
dataset2 = np.array(dataset)    
print(dataset2.shape)

x_train = dataset2[:,0:4]
y_train = dataset2[:,4]


print(x_train.shape)
print(y_train.shape)


(50, 5)
(50, 4)
(50,)


In [3]:
y_train

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8])

In [4]:
import keras
from keras.utils import np_utils

y_train2 = np_utils.to_categorical(y_train)

In [5]:
y_train2

array([[0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0.

In [7]:
one_hot_vec_size = y_train2.shape[1]
one_hot_vec_size

9

In [1]:
from PIL import Image
import os, glob, numpy as np
from sklearn.model_selection import train_test_split

In [2]:
img = Image.open('../Data/Driver Drowsiness Dataset (DDD)/Original_dataset/Drowsy/A0001.png')

In [5]:
pimg = np.array(img)
pimg

array([[[ 63,  49,  31],
        [ 62,  48,  31],
        [ 62,  48,  29],
        ...,
        [ 87,  67,  48],
        [ 87,  67,  48],
        [ 88,  68,  49]],

       [[ 63,  50,  32],
        [ 62,  49,  31],
        [ 60,  47,  29],
        ...,
        [ 88,  68,  49],
        [ 88,  68,  49],
        [ 88,  68,  49]],

       [[ 63,  51,  32],
        [ 62,  49,  31],
        [ 60,  47,  29],
        ...,
        [ 88,  68,  49],
        [ 88,  68,  49],
        [ 88,  68,  49]],

       ...,

       [[255, 255, 239],
        [255, 255, 239],
        [255, 255, 240],
        ...,
        [255, 255, 254],
        [255, 255, 254],
        [255, 255, 255]],

       [[254, 251, 237],
        [254, 251, 237],
        [254, 251, 239],
        ...,
        [254, 253, 250],
        [254, 253, 250],
        [254, 252, 250]],

       [[251, 243, 233],
        [252, 244, 234],
        [252, 244, 235],
        ...,
        [254, 251, 244],
        [252, 248, 242],
        [252, 245, 241]]

In [1]:
import numpy as np
import cv2


img = cv2.imread('../Data/Driver Drowsiness Dataset (DDD)/Original_dataset/Drowsy/A0001.png', cv2.IMREAD_COLOR)
#img = Image.open('../Data/Driver Drowsiness Dataset (DDD)/Original_dataset/Drowsy/A0001.png')

print('img.shape ', img.shape)


h, w, c = img.shape

print('height ', h)
print('width ', w)
print('channel ', c)

img.shape  (227, 227, 3)
height  227
width  227
channel  3
